Add emptyView
djud17-org/SB-MDEditor pull request #20
Opened 2023-04-20 17:58 UTC by zzzarya

- Добавил emptyView

<img width="253" alt="image" src="https://user-images.githubusercontent.com/109965569/233449244-f79f0092-de35-4548-8a1c-e081e87206ff.png">

2023-04-20 18:00 UTC, zzzarya commented
-Файл MDViewData

Нейминг по-моему так себе. Помогите с названием плиз

2023-04-20 18:17 UTC, SShliakhin requested changes

2023-04-20 18:17 UTC, SShliakhin commented on SB-MDEditor/Library/OptionalViews/MDViewData.swift
> +struct MDViewData {
EmptyInputData

2023-04-20 18:17 UTC, SShliakhin commented on SB-MDEditor/Library/OptionalViews/MDViewData.swift
> +	static let EmptyViewData = MDViewData(
emptyFolder

2023-04-20 18:17 UTC, SShliakhin commented on SB-MDEditor/Library/OptionalViews/MDViewData.swift
> +	static let ResentFileData = MDViewData(
noResentFiles

2023-04-20 19:15 UTC, djud17 requested changes
Есть несколько комментариев. В моем представлении когда ты только создаешь сущность все свойства и методы прописываются в основном теле, за исключением подписи на протоколы. В дальнейшем при разработке новая функциональность добавляется как раз через расширения и обертки.

2023-04-20 19:15 UTC, djud17 commented on SB-MDEditor/Library/OptionalViews/EmptyView.swift
> +}
Отсутствуют метки MARK

2023-04-20 19:15 UTC, djud17 commented on SB-MDEditor/Library/OptionalViews/EmptyView.swift
> +}
Для чего данные функции помещать в расширение? Ты же не добавляешь функциональность, а только создаешь класс

2023-04-20 19:15 UTC, djud17 commented on SB-MDEditor/Library/OptionalViews/EmptyView.swift
> +	}
Не уверен, что стоит ради инициализации пустого ImageView выделять целую функцию)

2023-04-20 19:15 UTC, djud17 commented on SB-MDEditor/Library/OptionalViews/MDViewData.swift
> +	static let EmptyViewData = MDViewData(
+ с маленькой буквы имена свойств

2023-04-20 19:15 UTC, djud17 commented on SB-MDEditor/Library/OptionalViews/MDViewData.swift
> +		message: "Empty folder"
Строки лучше выносить в константы. Можно например сделать private enum Constants только для этого файла

2023-04-20 19:15 UTC, djud17 commented on SB-MDEditor/Library/OptionalViews/MDViewData.swift
> +	static let ResentFileData = MDViewData(
Также с маленькой буквы

2023-04-20 20:03 UTC, SShliakhin requested changes
почти все ок
- вынести строки в константы через enum Appearance
- сделать описание публичного метода

По поводу приватного расширения все ок, это будет нашим стилем. Возможно нам потребуется вернуться и донастроить свойство картинки так что комментарии Давида преждевременны, сейчас не хватает опыта подсказать какие конкретно свойства нужны.

2023-04-20 20:03 UTC, SShliakhin commented on SB-MDEditor/Library/OptionalViews/EmptyView.swift
> +	func update(with data: EmptyInputData) -> Self {
В первый раз не заметил - это публичный метод, нужно описание

2023-04-20 20:03 UTC, SShliakhin commented on SB-MDEditor/Library/OptionalViews/EmptyInputData.swift
>  		message: "Empty folder"
Раз мы здесь, вынеси строку, как я уже показывал, в Appearance и преврати в одноименную константу внизу файла, а здесь будешь ее вызывать.

2023-04-20 20:03 UTC, SShliakhin commented on SB-MDEditor/Library/OptionalViews/EmptyInputData.swift
>  		message: "No recent file"
Здесь тоже самое: вынеси строку, как я уже показывал, в Appearance и преврати в одноименную константу внизу файла, а здесь будешь ее вызывать.

2023-04-20 23:37 UTC, SShliakhin requested changes
продолжаем развиваться, есть недочеты

2023-04-20 23:37 UTC, SShliakhin commented on SB-MDEditor/Library/OptionalViews/EmptyView.swift
> +	/// Функция для обновления View на EmptyViewProvider
ты наверно немного запутался, метод не для этого (старайся не писать больше слово функция - у нас только методы))) )
Метод обновляет вью новыми данными
еще должен был появится параметр в нем тоже надо написать что модель: мессадж и картинка

update мы будем использовать везде в приложении, где захотим использовать EmptyView он не только для просмотра вьюхи

2023-04-20 23:37 UTC, SShliakhin commented on SB-MDEditor/Library/OptionalViews/EmptyInputData.swift
> +		static let noResentFilesMessage = "No recent file"
мы сделаем из тебя программиста) хорошие названия, но упустил "... files"

2023-04-20 23:37 UTC, SShliakhin commented on SB-MDEditor/Library/OptionalViews/EmptyView.swift
>  	private lazy var emptyTextLabel = makeEmptyTextLabel()
раз мы все опять правим, то здесь можем улучшить - emptyMessageLabel - в такт твоим хорошим именам в структуре модельки, соответственно подправль и метод make...

2023-04-20 23:46 UTC, SShliakhin commented
еще правда у тебя конфликт нехороший на этой ветке, возможно у тебя опять был кривой старт, надо подумать почему так получилось
<img width="456" alt="image" src="https://user-images.githubusercontent.com/71236551/233509168-ececdc2a-5f50-4a10-95fd-ee07158ad3b5.png">

2023-04-22 22:07 UTC, SShliakhin approved these changes

2023-04-23 11:05 UTC, closed without merging