Feature 9&10: Добавлены RecentFiles и Menu view #9 #10
djud17-org/SB-MDEditor pull request #21
Opened 2023-04-20 22:41 UTC by djud17

Реализовано с помощью Compositional Layout для одного collectionView с разными секциями. Поэтому сделал в одной ветке, так было удобнее в процессе разработки. На данный момент заполнил тестовыми данными, при реализации логики - заменить на актуальные данные. Единственное не смог придумать, как реализовать предпросмотр файла на обложке, но если честно даже кажется, что это и не так необходимо - все равно по данному коду невозможно по предпросмотру понять что там.

2023-04-21 05:28 UTC, SShliakhin requested changes
Много понравилось, но у тебя, к сожалению, не получилось сделать задуманное. MainView недопиленная, ее нельзя переиспользовать, так же и в MainViewController нельзя запихать любую вью.
Выглядит все красиво и чисто, почти идеально, но стилистику которую я задал начальный проектом и которую пытаюсь привить ребятам у тебя не выдерживается. Я создал другую фичевую ветку: feature/9&10-mainView в ней я поправил одну из ячеек в стиле который хочу выдерживать при создании вьюшек, добавил некоторые улучшения по регистрации ячеек колекции - смотри изменения по коммитам. Предлагаю тебе продолжить работу в новой ветке и привести все к единому стилю.
Очень понравилось как ты скрыл модельку для ячейки - беру это себе на вооружение. Спасибо.

2023-04-21 05:28 UTC, SShliakhin commented on SB-MDEditor/Assets/MD_Bandle/M2_Testing/M2L1_GitFlow/GitInstruction.md
А подскажи, почему в твоем PR появились файлы md, которые вроде бы уже были добавлены ранее?

2023-04-21 07:15 UTC, djud17 commented on SB-MDEditor/Assets/MD_Bandle/M2_Testing/M2L1_GitFlow/GitInstruction.md
Спасибо за комментарии, отвечу по порядку.
Не понимаю, для чего нужно задавать констрейты в том виде, в котором ты сделал. Это никак не упрощает код, суть осталась такой же, просто зачем то выдумано другое исполнение от которого ничего не меняется опять же.
Не понимаю для чего нужно так усложнять использование View и Контроллера. Так никто не делает. Это не те компоненты, которые переиспользуются. Контроллер и вью работают в связке. Говорю тебе по опыту боевых проектов.
На счет файлов не могу сказать почему pr отобразились, я их не трогал и не комиттил.

Не нужно ничего делать на будущее из разряда "возможно пригодится", это нагромождение кода и файлов, которое копится и мешает. Сложно что-то делать, когда не видишь в этом смысла или какой то пользы.

2023-04-24 22:03 UTC, SShliakhin approved these changes
Все замечания опциональные с заделом на будущее. Функции со сборкой модулей переехали в другой файл, надеюсь это поможет решить конфликты.

2023-04-24 22:03 UTC, SShliakhin commented on SB-MDEditor/Modules/Main/MainViewController.swift
>  	func doSomething() {
это мы будем чистить в следующей итерации?

2023-04-24 22:03 UTC, SShliakhin commented on SB-MDEditor/Modules/Main/View/MainView.swift
Опционально: я стараюсь разделять публичные и приватные методы с помощью расширений

2023-04-24 22:03 UTC, SShliakhin commented on SB-MDEditor/Modules/Main/View/MainView.swift
> +	/// Функция для установки источника данных коллекции
на будущее - работаем с методами

2023-04-24 22:03 UTC, SShliakhin commented on SB-MDEditor/Modules/Main/View/MainView.swift
> +			top: 0,
на будущее - можно .zero - чтобы цифрами не пахло)

2023-04-24 22:03 UTC, SShliakhin commented on SB-MDEditor/Services/SectionManager.swift
> +	/// Функция позволяет получить доступные секции для коллекции.
на будущее  - используй Метод, а еще лучше вообще опускай, типа "Возвращает секции для коллекции"

2023-04-24 22:03 UTC, SShliakhin commented on SB-MDEditor/App/Di/Di+ModuleFactory.swift
Конечно стоит попытаться решить конфликты, но все функции в ветке задания переехали в другой файл, сорри

2023-04-25 15:14 UTC, zzzarya approved these changes

2023-04-25 18:49 UTC, djud17 commented on SB-MDEditor/Modules/Main/MainViewController.swift
>  	func doSomething() {
Поправил

2023-04-25 18:50 UTC, djud17 commented on SB-MDEditor/Modules/Main/View/MainView.swift
> +	/// Функция для установки источника данных коллекции
Поправил

2023-04-25 18:50 UTC, djud17 commented on SB-MDEditor/Modules/Main/View/MainView.swift
Поправил

2023-04-25 18:50 UTC, djud17 commented on SB-MDEditor/Modules/Main/View/MainView.swift
> +			top: 0,
Поправил

2023-04-25 18:50 UTC, djud17 commented on SB-MDEditor/Services/SectionManager.swift
> +	/// Функция позволяет получить доступные секции для коллекции.
Поправил

2023-04-25 18:50 UTC, djud17 commented on SB-MDEditor/App/Di/Di+ModuleFactory.swift
Вроде все конфликты решил, надеюсь ничего не сломал)))

2023-04-25 18:53 UTC, merged