26 File manager
djud17-org/SB-MDEditor pull request #34
Opened 2023-04-25 18:31 UTC by djud17

Сервис реализует 3 метода

- Возвращает список файлов по переданному url
- Возвращает содержимое файла по переданному url
- Возвращает файл с его свойствами

2023-04-25 21:00 UTC, SShliakhin requested changes
Давид, надеюсь я смог передать идею

2023-04-25 21:00 UTC, SShliakhin commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	init(fileStorage: IFilesStorageProvider) {
не хватает корня для bundle и documents - хотелось бы чтобы мы через конструктор сразу настроили необходимые пути и избавились от лишних проверок на `Bundle.main.resourcePath` и по Documents тоже
Я в примерах назвал их соответственно: rootBundle и rootDocs

2023-04-25 21:00 UTC, SShliakhin commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	private let fileManager = FileManager.default
я подумал что нам здесь так же необходимо наличие `var currentPath: String` - для фиксации текущего расположения в ФС в приложении, при этом через didSet на изменение пути сразу получать набор файлов

2023-04-25 21:00 UTC, SShliakhin commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	private let fileStorage: IFilesStorageProvider
нужен, для фиксации открытых файлов - когда передаешь контент файла, сразу заносишь этот файл в хранилище - строкой - полный путь
ранее думал чтобы фиксировать и текущий путь в ФС в приложении, но при наличие этого сервиса считаю это дублированием - и можно этот функционал выпиливать из IFilesStorageProvider

2023-04-25 21:00 UTC, SShliakhin commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	private let fileManager = FileManager.default
если currentPath.isEmpty - нужно возвращать список заранее подготовленных файлов-каталогово, что то типа:
```swift
var currentPath: String {
		didSet {
			var newList: [File] = []
			if currentPath.isEmpty {
				var rootDocs = File.BasePath.baseDocs
				rootDocs.path = docs
				newList.append(rootDocs)

				var rootBundle = File.BasePath.baseBundle
				rootBundle.path = bundle
				newList.append(rootBundle)

				files = newList
			} else {
				files = listFilesFromPath()
			}
		}
	}
```

```swift
extenstion File {
	enum BasePath {
		static var baseDocs: File = .init(
			name: "** Документы **",
			path: "",
			ext: "",
			size: 0,
			isFile: false,
			isDir: true,
			creationDate: Date(),
			modificationDate: Date()
		)

		static var baseBundle: File = .init(
			name: "** Бандл **",
			path: "",
			ext: "",
			size: 0,
			isFile: false,
			isDir: true,
			creationDate: Date(),
			modificationDate: Date()
		)
	}
```

2023-04-25 21:00 UTC, SShliakhin commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +			print("Невозможно найти файлы")
с принтами я если честно не знаю что делать, swiftLint на них вроде не ровно дышит

2023-04-25 21:00 UTC, SShliakhin commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +			if let type = attributes[FileAttributeKey.type] as? FileAttributeType,
опционально конечно, но я бы оставил как было раньше isDir и isFile

2023-04-25 21:00 UTC, SShliakhin commented on SB-MDEditor/Models/File.swift
> +	var size: UInt64
var size: UInt64 = .zero

2023-04-25 21:00 UTC, SShliakhin commented on SB-MDEditor/Models/File.swift
> +final class File {
а зачем класс?

2023-04-25 21:00 UTC, SShliakhin commented on SB-MDEditor/Models/File.swift
> +	var fullname: String {
в случае с файлами заглушками для бандла и доков для начальной навигации, тут надо подумать и изменить, я например делал так:
```swift
var fullname: String {
		get {
			if name.hasPrefix("** ") && name.hasSuffix(" **") {
				return "\(path)"
			} else {
				return "\(path)/\(name)"
			}
		}
	}
```

в мое случае они были
<img width="453" alt="image" src="https://user-images.githubusercontent.com/71236551/234399268-b31c02c7-3b4b-4269-8c40-2877893160b3.png">

2023-04-25 21:00 UTC, SShliakhin commented on SB-MDEditor/Models/File.swift
> +	func loadFileBody() -> String {
этот метод здесь не нужен

2023-04-25 21:00 UTC, SShliakhin commented on SB-MDEditor/Models/File.swift
> +extension File {
кажется нужен private и если есть публичные то подписать

2023-04-25 21:00 UTC, SShliakhin commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	func getFileList(for fileUrl: URL) -> [String]
если будет currentPath, то параметр не нужен или вообще можно сделать свойством

2023-04-25 21:00 UTC, SShliakhin commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	func getFileContent(for fileUrl: URL) -> String?
я бы просто передавал file: File или строку

2023-04-25 21:00 UTC, SShliakhin commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	private let fileManager = FileManager.default
еще свойство private var files: [Files]

2023-04-25 21:28 UTC, djud17 commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	func getFileList(for fileUrl: URL) -> [String]
Так можно же просто передать currentPath в функцию, если надо
Либо я не очень понимаю про что ты

2023-04-25 21:28 UTC, djud17 commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	func getFileContent(for fileUrl: URL) -> String?
Ну я здесь решил сделать, чтоб было единообразие. По сути если будем передавать файл - все равно будем url вытаскивать

2023-04-25 21:28 UTC, djud17 commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	private let fileStorage: IFilesStorageProvider
Ну по идее мне кажется это не здесь надо делать
А там, где будет метод открытия файла и мы дергаем разные сервисы, на мой взгляд.

2023-04-25 21:28 UTC, djud17 commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	private let fileManager = FileManager.default
Как будто бы кажется, что не этот сервис должен отвечать за наполнение файлами

2023-04-25 21:28 UTC, djud17 commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	init(fileStorage: IFilesStorageProvider) {
Может в какие нибудь константы вынести? У нас могут возникнуть ситуации, когда необходимо будет передать что то другое в bundle?

2023-04-25 21:28 UTC, djud17 commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +			print("Невозможно найти файлы")
Можно сделать какой нибудь менеджер ошибок, который будет показывать alert с ошибкой, например

2023-04-25 21:28 UTC, djud17 commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +			if let type = attributes[FileAttributeKey.type] as? FileAttributeType,
Тут я согласен с Кириллом, это может привести к некорректным случаям, когда из за ошибки будут оба true или false. А так есть конкретный тип и эти типы, можно расширять в будущем, если вдруг понадобиться.

2023-04-25 21:28 UTC, djud17 commented on SB-MDEditor/Models/File.swift
> +final class File {
Потому что в данном случае нам не нужно, чтоб создавались копии. 
Например, в одном месте мы поменяем имя файла - тогда везде в приложении будет актуальная информация. и тд

2023-04-25 21:28 UTC, djud17 commented on SB-MDEditor/Models/File.swift
> +	var size: UInt64
я хотел избежать здесь задачи значений по умолчанию, чтоб избежать ситуации с некорректной информацией. А так создаешь файл и сразу проставляешь все поля в конструкторе.

2023-04-25 21:28 UTC, djud17 commented on SB-MDEditor/Models/File.swift
> +	var fullname: String {
Ну по идее, мы можем вообще убрать fullName. Пока не очень понимаю, нужен ли он нам.
Он был в модели Кирилла

2023-04-25 21:28 UTC, djud17 commented on SB-MDEditor/Models/File.swift
> +extension File {
Поправил

2023-04-25 21:28 UTC, djud17 commented on SB-MDEditor/Models/File.swift
> +	func loadFileBody() -> String {
Поправил, согласен

2023-04-25 21:36 UTC, SShliakhin commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	init(fileStorage: IFilesStorageProvider) {
мы через конструктор же передаем начальные пути, можем передавать и уже подготовленные константы, для констант я предлагаю сделать очередное расширение в Theme. Я думаю констант в самом сервисе быть не должно.

2023-04-25 21:41 UTC, SShliakhin commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	private let fileManager = FileManager.default
если есть предложения, то могу выслушать.
Смотри мы настраиваем сервис - даем ему начальный путь, он нам сразу список файлов подготовил + по запросу содержимое файла
Экран по открытию файлов полностью на нем может быть завязан - открывается - обращается к сервису, сервис в ответ на тебе текущую папку и список файлов в нем, и ждет дальнейших указаний)

2023-04-25 21:43 UTC, SShliakhin commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	private let fileStorage: IFilesStorageProvider
открываем мы файл через этот сервис, ведь так? Он же и может сделать пометку о файле в хранилище, логично?
Может быть я не совсем тебя понял, разверни, предыдущий свой тезис

2023-04-25 21:44 UTC, SShliakhin commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +			print("Невозможно найти файлы")
пока я думаю можно оставить так, времени жалко, я так уточнил

2023-04-25 21:45 UTC, SShliakhin commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +			if let type = attributes[FileAttributeKey.type] as? FileAttributeType,
Да у меня были сомнения, не мог вспомнить почему, спасибо что напомнил.

2023-04-25 21:46 UTC, SShliakhin commented on SB-MDEditor/Models/File.swift
> +	var fullname: String {
нужен он очень удобен!

2023-04-25 21:49 UTC, SShliakhin commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	func getFileList(for fileUrl: URL) -> [String]
я приводил пример выше, как сервис реагирует на изменение currentPath - он сразу же готовит файлы - свойство которое хранит файлы может быть private и тогда публичная функция нужна чтобы до него достучаться или сразу же делать ее публичной - я за публичную функцию короче)

2023-04-25 21:52 UTC, SShliakhin commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	func getFileContent(for fileUrl: URL) -> String?
как раз нет, url.path - это строка и URL используется только для внешних ссылок, типа documents, я хочу сразу от url избавиться

2023-04-25 22:04 UTC, SShliakhin commented on SB-MDEditor/Models/File.swift
> +	var size: UInt64
тогда правильно

2023-04-25 22:07 UTC, SShliakhin commented on SB-MDEditor/Models/File.swift
> +final class File {
разумно, только я пока не могу представить ситуации, где это у нас сейчас стреляет, хорошо пусть будет класс!

2023-04-26 10:31 UTC, zzzarya approved these changes

2023-04-27 14:51 UTC, djud17 commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	init(fileStorage: IFilesStorageProvider) {
Что касается конструктора - есть ситуации, когда эти пути меняются? если да, тогда надо выносить в конструктор, если нет - достаточно в константы)
Я и имел в виду общие константы)

2023-04-27 14:54 UTC, djud17 commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	private let fileManager = FileManager.default
Смотри у данной сущности должна быть только одна ответственность по SOLID - работа с файлами (список файлов, контент и тд). Наполнение файлами это уже другая ответственность и на мой взгляд их нужно разделить. Например сделать какой то репозиторий - который будет отвечать за наполнение файлами. Это позволит нам управлять более гибко данными. Например, если мы захотим брать файлы из сети - просто подменяем репозиторий.

2023-04-27 14:57 UTC, djud17 commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	private let fileStorage: IFilesStorageProvider
Это опять же к моему комментарию про ответственности. Фиксация открытых файлов это что то типо аналитики и это не нужно имплементировать в конкретную часть процесса открытия файлов.
На мой взгляд это лучше вынести в более глобальное место, по идее в интерактор, которому контроллер сообщил что пользователь нажал на файл. Интерактор владеет и общается с сервисами и сообщает fileManager - открой файл, fileStorage - зафиксируй открытый файл, и тд. Иначе у нас получится цепочка сервисов зависящих друг от друга.

2023-04-27 14:59 UTC, djud17 commented on SB-MDEditor/Models/File.swift
> +	var fullname: String {
Поправил

2023-04-27 15:00 UTC, djud17 commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	func getFileContent(for fileUrl: URL) -> String?
Поправил

2023-04-27 15:13 UTC, SShliakhin commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	init(fileStorage: IFilesStorageProvider) {
Воспринимай пути как часть первоначальной настройки сервиса - для настройки мы можем использовать как константы, так напрямую передавать другие пути в конструктор. Сервис не должен использовать константы приложения - мы его делаем тогда жестким и связанным с конкретным приложением.

2023-04-27 15:29 UTC, SShliakhin commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	private let fileManager = FileManager.default
Боюсь что, перешли на уровень холивара. Вместо доп репозитория мы также можем написать другой сервис под этим же протоколом для получения файлов из сети. Твое предложение может быть рассмотрено, но требует введения новых абстракций и объектов, а времени нет, динамика с которой мы выполняем ДЗ тоже не очень. Настало время включать вето ТЛ: 
- сделай, пожалуйста публичный currentPath, при его изменении должен сформироваться массив files: [File] и мы его можем получить через публичный метод снаружи, а также 
- сделай публичный/или доступный по функции currentFile - который заполняется когда кто то запросит контент файла - при его изменение дергай .add у сервиса хранения недавно открытого файла.

Ответственность этого сервиса: 
- хранить текущие путь и файл, 
- выдавать список файлов по текущему пути
- выдавать содержимое указанного файла по полному пути в виде строки, 
- дергать сервис по хранению недавно открытых файлов - передавай полный путь в виде строки

2023-04-27 15:36 UTC, SShliakhin commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	private let fileStorage: IFilesStorageProvider
С учетом имеющегося времени, я не вижу в цепочке ничего плохого, плюс моего предложенного решения:
- сэкономим время
- открытие и сохранение файла как недавно открытого в одном месте, как единая транзакция

Твое предложение: надо еще обдумать и куда-то вклинить с учетом внедрения доп зависимостей
- время
- кодирование
- проверка

Надеюсь на понимание, получим плохую ОС - изменим.

2023-04-27 15:39 UTC, SShliakhin requested changes
Прописал старые/новые ответственности для сервиса по моему видению с учетом нехватки времени - прошу принять как вариант решения

2023-04-27 15:39 UTC, djud17 commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	private let fileManager = FileManager.default
Причем тут холивар, если я тебе написал конкретную аргументацию и даже предложил решение. Ты сам же писал про принципы solid и прочие правила. Если нет времени, это не значит, что нужно делать лишь бы как.
Не удивлюсь, если потом и Кирилл на это укажет.
Я абсолютно не согласен с данным решением, но видимо переубедить тебя не удалось. Реализую твою задумку

2023-04-27 15:55 UTC, djud17 commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	init(fileStorage: IFilesStorageProvider) {
Поправил

2023-04-27 15:55 UTC, djud17 commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	private let fileManager = FileManager.default
Поправил

2023-04-27 15:57 UTC, djud17 commented on SB-MDEditor/App/Services/FileSystemManager.swift
> +	func getFileList(for fileUrl: URL) -> [String]
Поправил

2023-04-28 02:16 UTC, SShliakhin commented
Добавил сервис:
```swift
protocol ILocalFilesProvider {
	/// Возвращает текущий путь к файлам.
	/// - Parameter path: путь который хотим установить.
	/// - Returns: текущий путь, может отличаться от переданного.
	func setPath(_ path: String) -> String

	/// Возвращает строковое содержимое файла, если смогли его получить, иначе nil.
	/// В случае успеха запоминает файл в списке ранее прочитанных.
	/// - Parameter path: путь к файлу.
	/// - Returns: строковое содержимое файла или nil.
	func readFileAtPath(_ path: String) -> String?

	/// Возвращает список файлов по текущему пути.
	/// - Returns: списко файлов.
	func getFiles() -> [File]

	/// Возвращает текущий путь к файлам.
	/// - Returns: текущий путь к файлам.
	func getPath() -> String
}
```

2023-04-28 02:22 UTC, SShliakhin commented
Также изменил сервис по хранению недавно открытых файлов:
```swift
protocol IFilesStorageProvider {
	/// Возвращает список имен недавно открытых файлов.
	/// - Returns: список имен недавно открытых файлов.
	func getRecentFiles() -> [String]

	/// Добавить имя в список недавно открытых файлов.
	/// - Parameter fileName: имя файла
	func add(fileName: String)
}
```
реализацию сделал классом

2023-04-28 07:23 UTC, djud17 reviewed
Апрувить не могу - так как мой pr
Прокомментировал моменты, которые бросились в глаза

2023-04-28 07:23 UTC, djud17 commented on SB-MDEditor/App/Services/FilesStorageProvider.swift
>  }
зачем делать вычисляемое свойство, которое никогда не меняется? Ключ можно вынести в константы для этого экрана, как ты делал в других местах - Appearance

2023-04-28 07:23 UTC, djud17 commented on SB-MDEditor/App/Services/FilesStorageProvider.swift
>  		fileNames.insert(fileName, at: 0)
Публичные методы тоже в расширении теперь надо прописывать?

2023-04-28 07:23 UTC, djud17 commented on SB-MDEditor/App/Services/LocalFilesProvider.swift
> +
для чего нам хранить здесь расширения файлов? расширение мы спокойно можем получить из имени файла - если это нам необходимо. Но до текущего момента такой необходимости не было.

2023-04-28 07:23 UTC, djud17 commented on SB-MDEditor/App/Services/LocalFilesProvider.swift
> +	private var currentPath = "" {
ты же писал, что это публичное свойство

2023-04-28 07:23 UTC, djud17 commented on SB-MDEditor/App/Services/LocalFilesProvider.swift
> +	}
опять публичные методы в расширении
вместо таких методов лучше делать вычисляемые свойства

2023-04-28 07:23 UTC, djud17 commented on SB-MDEditor/App/Services/LocalFilesProvider.swift
> +		return false
можно сделать одной строчкой
baseFilePaths.filter { $0.hasPrefix(item.fullname) }.count > 0

2023-04-28 07:23 UTC, djud17 commented on SB-MDEditor/App/Services/LocalFilesProvider.swift
> +		let newList = list
а list нельзя использовать? Зачем дублировать переменную?

2023-04-28 07:23 UTC, djud17 commented on SB-MDEditor/App/Services/LocalFilesProvider.swift
> +			}
подобное условие можно добавить в цикл через where.
Будет меньше заходов в цикл и чище код

2023-04-28 07:23 UTC, djud17 commented on SB-MDEditor/App/Services/LocalFilesProvider.swift
> +			if let fileItem = getFile(withName: item, atPath: currentPath) {
guard let

2023-04-28 07:23 UTC, djud17 commented on SB-MDEditor/App/Services/LocalFilesProvider.swift
> +				}
подобное нужно делать через switch.
Потому что если добавиться еще один case - switch подсветит ошибку, а подобные условия останутся незамеченными и можно забыть

2023-04-28 07:23 UTC, djud17 commented on SB-MDEditor/Models/File.swift
> +	}
Почему ты сделал данные функции приватными? Разве они не нужны нам будут для корректного отображения информации о файле?

2023-04-28 07:23 UTC, djud17 commented on SB-MDEditor/Resources/Theme/Theme+Constants.swift
> +		// swiftlint:disable:next closure_body_length
кажется, что отключение подобных правил говорит о том, что лучше пересмотреть тело свойства

2023-04-28 07:23 UTC, djud17 commented on SB-MDEditor/Resources/Theme/Theme+Constants.swift
> +			return ""
guard let

2023-04-28 12:26 UTC, SShliakhin commented on SB-MDEditor/App/Services/FilesStorageProvider.swift
>  }
это расширение протокола, то что будет всегда у тех кто будет подписываться

2023-04-28 12:29 UTC, SShliakhin commented on SB-MDEditor/App/Services/FilesStorageProvider.swift
>  		fileNames.insert(fileName, at: 0)
вкусовщина конечно, я выделил ту часть, которая конформит протокол. Активно использую расширения для деление кода на смысловые блоки. Хочешь используй, хочешь нет.

2023-04-28 12:34 UTC, SShliakhin commented on SB-MDEditor/App/Services/LocalFilesProvider.swift
> +
это логика работы нашего сервиса 
- начальные пути baseFilePaths, 

ограничение на файлы: 
- конкретно не можем обрабатывать файлы - exceptionFiles и 
- работаем только с такими расширениями exts

2023-04-28 12:35 UTC, SShliakhin commented on SB-MDEditor/App/Services/LocalFilesProvider.swift
> +	private var currentPath = "" {
мне нужен был доступ к этому: я предлагал публичное свойство либо доступ через функцию, реализовал доступ через функции

2023-04-28 12:41 UTC, SShliakhin commented on SB-MDEditor/App/Services/LocalFilesProvider.swift
> +	}
мы же все пишем по разному, я тоже испытываю разные чувства когда читаю чужой код, что то нравится, что то сильно нравится).
А чем лучше делать вычисляемые свойства?

2023-04-28 12:43 UTC, SShliakhin commented on SB-MDEditor/App/Services/LocalFilesProvider.swift
> +		return false
у меня кажется чуточку быстрее

2023-04-28 12:47 UTC, SShliakhin commented on SB-MDEditor/App/Services/LocalFilesProvider.swift
> +		let newList = list
да можно, замылилось

2023-04-28 12:54 UTC, SShliakhin commented on SB-MDEditor/App/Services/LocalFilesProvider.swift
> +			}
некрасивое условие через  where получится и сложнее из-за этого читать, а внутри цикла еще условия, 
как по мне, меньше кода - это не значит что он сразу чище становится

2023-04-28 13:47 UTC, SShliakhin commented on SB-MDEditor/App/Services/LocalFilesProvider.swift
> +				}
наверно в нашем случае не актуально, но идея мне нра
Вот что в итоге может получится, как?
```swift
func getFilesAtCurrentPath() -> [File] {
		guard let list = try? fileManager.contentsOfDirectory(atPath: currentPath) else { return [] }

		var file: [File] = []
		var directory: [File] = []

		for item in list where !item.hasPrefix(".") {

			guard let fileItem = getFile(withName: item, atPath: currentPath) else { continue }

			switch fileItem.filetype {
			case .file:
				guard exts.contains(where: { $0 == fileItem.ext }) else { continue }
				guard !exceptionFiles.contains(where: { $0 == fileItem.fullname }) else { continue }

				file.append(fileItem)
			case .directory:
				directory.append(fileItem)
			}
		}

		file.sort { $0.name < $1.name }
		directory.sort { $0.name < $1.name }
		return directory + file
	}
```

2023-04-28 13:49 UTC, SShliakhin commented on SB-MDEditor/App/Services/LocalFilesProvider.swift
> +			if let fileItem = getFile(withName: item, atPath: currentPath) {
в следующем комментарии реализован

2023-04-28 13:50 UTC, SShliakhin commented on SB-MDEditor/Models/File.swift
> +	}
так все что нам надо уже есть в модельке File

2023-04-28 13:51 UTC, SShliakhin commented on SB-MDEditor/Resources/Theme/Theme+Constants.swift
> +		// swiftlint:disable:next closure_body_length
Согласен, долго думал, но я не нашел другого варианта, предложи свой

2023-04-28 13:57 UTC, SShliakhin commented on SB-MDEditor/Resources/Theme/Theme+Constants.swift
> +			return ""
Заменил, спс

2023-04-28 14:03 UTC, SShliakhin commented on SB-MDEditor/App/Services/LocalFilesProvider.swift
> +				}
Сделал этот вариант

2023-04-28 14:13 UTC, SShliakhin approved these changes

2023-04-28 18:40 UTC, merged