Feature/25 create about screen
djud17-org/SB-MDEditor pull request #35
Opened 2023-04-27 11:11 UTC by chuRealOff

Не реализовал обёртку экрана с помощью UINavigationController.
Не до конца понимаю, как это сделать оптимальным образом, принимая во внимание текущую структуру проекта.

2023-04-27 15:17 UTC, djud17 requested changes

2023-04-27 15:17 UTC, djud17 commented on SB-MDEditor/App/Di/Di.swift
>  		let navigationVC = UINavigationController(rootViewController: viewController)
Так вот же ты оборачиваешь в навигейшн контроллер? или я не понимаю про что ты)

2023-04-27 15:17 UTC, djud17 commented on SB-MDEditor/Modules/About/AboutInteractor.swift
> +}
Именование протоколов, начиная с I
И вообще очень странный префикс к сущностям About, понимаю, что это название модуля. Но я бы если честно переработал - немного смущает, когда читаешь, особенно если контекст забудется.

2023-04-27 15:17 UTC, djud17 commented on SB-MDEditor/Modules/About/AboutInteractor.swift
> +	private var presenter: AboutPresentationLogic?
зачем опциональность? также private let
Цикл разбивается в презентере - weak var

2023-04-27 15:17 UTC, djud17 commented on SB-MDEditor/Modules/About/AboutInteractor.swift
> +	}
публичная функция должна быть с документацией.
также если не получается прочитать файл - логично показать какую то ошибку.

2023-04-27 15:17 UTC, djud17 commented on SB-MDEditor/Modules/About/AboutPresenter.swift
> +	}
забыл документацию для публичной функции + именование протоколов с I
Также можно сделать тип ViewData, который и передавать контроллеру. Можешь посмотреть по аналогии с первым проектом. В случае если понадобиться еще какую то информацию передать не нужно будет все переписывать, а просто добавишь одно поле во ViewData и проинициализируешь)

2023-04-27 15:17 UTC, djud17 commented on SB-MDEditor/Modules/About/AboutRouter.swift
> +}
Именование протоколов + для чего эта сущность? Если ничего не делает зачем плодить бесполезный код)

2023-04-27 15:17 UTC, djud17 commented on SB-MDEditor/Modules/About/AboutViewController.swift
> +	private let interactor: AboutBusinessLogic?
Зачем опциональность опять же?)

2023-04-27 15:17 UTC, djud17 commented on SB-MDEditor/Modules/About/AboutViewController.swift
> +protocol AboutDisplayLogic: AnyObject {
Именование протокола + документация публичной функции

2023-04-27 15:17 UTC, djud17 commented on SB-MDEditor/Modules/About/AboutViewController.swift
> +	func setup() { }
зачем пустой метод?

2023-04-27 15:17 UTC, djud17 commented on SB-MDEditor/Modules/About/AboutViewController.swift
>  	}
Зачем пустой enum?

2023-04-28 20:54 UTC, SShliakhin commented on SB-MDEditor/Modules/About/AboutRouter.swift
> +}
здесь я прокоментирую:
AboutRoutingLogic подписан под протокол, который требует наличие этого свойства

2023-04-28 20:55 UTC, SShliakhin commented on SB-MDEditor/Modules/About/AboutViewController.swift
>  	}
здесь не видно, на что ты хотел обратить наше внимание

2023-04-29 09:36 UTC, chuRealOff commented on SB-MDEditor/Modules/About/AboutViewController.swift
> +protocol AboutDisplayLogic: AnyObject {
поправил

2023-04-29 09:37 UTC, chuRealOff commented on SB-MDEditor/Modules/About/AboutViewController.swift
> +	private let interactor: AboutBusinessLogic?
поправил

2023-04-29 09:46 UTC, chuRealOff commented on SB-MDEditor/Modules/About/AboutInteractor.swift
> +}
не придавал этому большое значение, но в действительности язык приходится поломать )
Переработал

2023-04-29 09:48 UTC, chuRealOff commented on SB-MDEditor/Modules/About/AboutInteractor.swift
> +	private var presenter: AboutPresentationLogic?
исправил

2023-04-29 09:48 UTC, chuRealOff commented on SB-MDEditor/App/Di/Di.swift
>  		let navigationVC = UINavigationController(rootViewController: viewController)
всё верно, но на тот момент времени мне не было об этом известно )

2023-04-29 09:50 UTC, chuRealOff commented on SB-MDEditor/Modules/About/AboutViewController.swift
> +	private let interactor: AboutBusinessLogic?
поправил

2023-04-29 09:51 UTC, chuRealOff commented on SB-MDEditor/Modules/About/AboutViewController.swift
> +	func setup() { }
метод заполнил созданием кнопки возврата на предыдущий экран в навигейшн баре

2023-04-29 09:55 UTC, chuRealOff commented on SB-MDEditor/Modules/About/AboutViewController.swift
>  	}
я также не понял сути вопроса

2023-04-29 09:56 UTC, chuRealOff commented on SB-MDEditor/Modules/About/AboutViewController.swift
> +protocol AboutDisplayLogic: AnyObject {
исправлено

2023-04-29 10:59 UTC, chuRealOff commented on SB-MDEditor/Modules/About/AboutPresenter.swift
> +	}
сделал

2023-05-01 23:19 UTC, closed without merging