Доработать экран Открыть документ
djud17-org/SB-MDEditor pull request #42
Opened 2023-05-04 19:36 UTC by zzzarya

-Добавил EmptyView

-Нужны пояснения по авто высоте ячейки

![image](https://user-images.githubusercontent.com/109965569/236311269-3c99b2cb-312b-4950-85a3-bce434e93db4.png)

2023-05-04 20:42 UTC, SShliakhin requested changes

2023-05-04 20:42 UTC, SShliakhin commented on SB-MDEditor/Modules/CreateDoc/CreateDocPresenter.swift
> +
здесь внимательности что ли, добавлена строка, файл просит обновления, удали эту строку, пожалуйста

2023-05-04 20:42 UTC, SShliakhin commented on SB-MDEditor/Modules/OpenDoc/OpenDocViewController.swift
> +		if viewModel.files.isEmpty { // Пока тут оставил, хз где лучше проверять
в updateView() будет правильнее

2023-05-04 20:42 UTC, SShliakhin commented on SB-MDEditor/Modules/OpenDoc/OpenDocViewController.swift
> +		setupEmptyView()
на самом деле правильнее размещать в table.bagroundView, так кажется

2023-05-04 20:42 UTC, SShliakhin commented on SB-MDEditor/Modules/OpenDoc/OpenDocViewController.swift
final class OpenDocViewController: UITableViewController - надо сделать обычный VC, а таблицу размещать как отдельную вьюху со всеми вытекающими по делегатам

2023-05-04 20:42 UTC, SShliakhin commented on SB-MDEditor/Modules/OpenDoc/OpenDocViewController.swift
```swift
navigationItem.leftBarButtonItem = UIBarButtonItem(
				title: "<<",
				style: .plain,
				target: self,
				action: #selector(returnToPreviousPath)
			)
```
заменить << картинкой

2023-05-04 20:45 UTC, SShliakhin commented
По автовысоте ячейки - нужно чтобы высота ячейки рассчитывалась автоматически по своему содержимому:
- в лайауте ячейки обязательно наличие bottom анкора
- необходимо прописать доп свойства для таблицы

2023-05-06 15:56 UTC, zzzarya commented
Не понимаю, как работать с высотой ячейки. Вместо ее вытягивания, сужаются элементы внутри ячейки

2023-05-06 18:45 UTC, SShliakhin requested changes
все сделал правильно, но организацию кода можно улучшить.
сделал предложение по лайауту ячейки, итоговый стек прижать по всем краям к contentView
что то у тебя опять изменения с EmptyView в файле проекта произошли, я на самом деле в главной ветке ввел это изменение - и у тебя конфликт из-за этого. Может быть стоит ей снова убрать таргет - конфликт должен исчезнуть, а когда вольешь изменения - он восстановится, я думаю

2023-05-06 18:45 UTC, SShliakhin commented on SB-MDEditor/Modules/OpenDoc/OpenDocCell/OpenDocCell.swift
static let identifier = "OpenDocCell" - можно уже удалить
Надписи сделать через make... в которых установишь шрифт и количество строк = 0
Картинку тоже через make... ей задать mode - aspectFit кажется
По лайауту попробуй использовать UIStackView(): один вертикальны для надписей и горизонтальный чтобы связать картинку и вертикальный с надписями

2023-05-06 18:45 UTC, SShliakhin commented on SB-MDEditor/Modules/OpenDoc/OpenDocViewController.swift
> +final class OpenDocViewController: UIViewController, UITableViewDataSource, UITableViewDelegate {
конформы для таблицы разбей по расширениям c MARK: -

2023-05-06 18:45 UTC, SShliakhin commented on SB-MDEditor/Modules/OpenDoc/OpenDocViewController.swift
>  	private lazy var emptyView = EmptyView()
эту вьюху объявляй в make... для таблицы и сразу присваивай background, гасить ее не надо, проверка будет в update

2023-05-06 18:45 UTC, SShliakhin commented on SB-MDEditor/Modules/OpenDoc/OpenDocViewController.swift
> +	private lazy var tableView = UITableView()
для таблицы make... где сразу все настройки c делегатами + emptyView

2023-05-06 18:45 UTC, SShliakhin commented on SB-MDEditor/Modules/OpenDoc/OpenDocViewController.swift
>  		setupTableView()
setupTableView() - после make... уже вроде не нужна

2023-05-06 18:45 UTC, SShliakhin commented on SB-MDEditor/Modules/OpenDoc/OpenDocViewController.swift
>  	private lazy var emptyView = EmptyView()
здесь кажется не прав, для нее make... - ссылка на нее нужна оказывается при проверке наличия данных, сорри

2023-05-06 18:45 UTC, SShliakhin commented on SB-MDEditor/Modules/OpenDoc/OpenDocViewController.swift
> +		UITableView.automaticDimension
да так!

2023-05-06 18:45 UTC, SShliakhin commented on SB-MDEditor/Modules/OpenDoc/OpenDocViewController.swift
> +		tableView.register(models: [OpenDocCellModel.self])
супер!

2023-05-06 18:45 UTC, SShliakhin commented on SB-MDEditor/Modules/OpenDoc/OpenDocViewController.swift
> +		tableView.estimatedRowHeight = 100
оставь 64, чем меньше тем лучше)

2023-05-06 18:45 UTC, SShliakhin commented on SB-MDEditor/Modules/OpenDoc/OpenDocViewController.swift
> +				image: Asset.icBack.image,
а это нормальная картинка, пришли скрин, плиз

2023-05-06 18:45 UTC, SShliakhin commented on SB-MDEditor/Modules/OpenDoc/OpenDocViewController.swift
> +		tableView.backgroundView = emptyView
это можно делать сразу в make... для таблицы

2023-05-06 18:45 UTC, SShliakhin commented on SB-MDEditor/Modules/OpenDoc/OpenDocViewController.swift
>  		return tableView.dequeueReusableCell(withModel: model, for: indexPath)
да все правильно, супер

2023-05-06 19:54 UTC, zzzarya commented on SB-MDEditor/Modules/OpenDoc/OpenDocViewController.swift
> +				image: Asset.icBack.image,
<img width="313" alt="image" src="https://user-images.githubusercontent.com/109965569/236644065-3127f668-43f8-421a-b64d-cbc9b92f93b6.png">

2023-05-06 19:55 UTC, zzzarya commented on SB-MDEditor/Modules/OpenDoc/OpenDocViewController.swift
>  		setupTableView()
Если уберу эти две строчки из setup в make, приложение падает 

<img width="523" alt="image" src="https://user-images.githubusercontent.com/109965569/236644119-2d90692b-c71c-45d3-8bbf-4142c745bc2a.png">

2023-05-06 20:05 UTC, SShliakhin commented on SB-MDEditor/Modules/OpenDoc/OpenDocViewController.swift
> +				image: Asset.icBack.image,
вроде гуд, интересно справа иконки можно как то поджать друг к другу?

2023-05-06 20:06 UTC, zzzarya commented on SB-MDEditor/Modules/OpenDoc/OpenDocCell/OpenDocCell.swift
Co stackView я не смогу сделать атрибуты пониже 
<img width="315" alt="image" src="https://user-images.githubusercontent.com/109965569/236644537-e5d3890a-a68b-4069-978a-67053aae6c6f.png">

2023-05-06 20:31 UTC, zzzarya commented on SB-MDEditor/Modules/OpenDoc/OpenDocViewController.swift
> +				image: Asset.icBack.image,
Вроде как это минимальная ширина, я по крайней мере пока не нашел

2023-05-08 12:26 UTC, closed without merging